project:
  type: website
  output-dir: docs

website:
  title: "R Workshop"
  navbar:
    left:
      - href: index.htmls
        text: Week 1

format:
  html:
    toc: true
    theme: cosmo
